### ISSUE TITLE
method name may be more pythonic?

### ISSUE THREAD

**Issue by barryz** [clamytoe/Cylon#2]
Method: `show_prev` `show_next`  can use `prev` `next` to instead ?

**Comment by clamytoe** [comment]
If you take a look at the tests you will see that in order to get the next and prev items, you simply use `next(obj)` and `prev(obj)`. The `show_` property methods simply *display/show* what is previous/next in relation to the current index without actually modifying the current index.

**Comment by clamytoe** [comment]
I made the change, hopefully it won't be confusing. Thanks for the suggestion.
